import { BillingPanel } from '@/Components/deals/billing-panel';
import { JobSheetPanel } from '@/Components/deals/job-sheet-panel';
import { StatusPanel } from '@/Components/deals/status-panel';
import { PageHeader } from '@/Components/page-header';
import { Badge } from '@/Components/ui/badge';
import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/Components/ui/card';
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from '@/Components/ui/empty';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/Components/ui/tabs';
import AppLayout from '@/Layouts/AppLayout';
import { formatDate, formatDateTime, formatMoney } from '@/lib/format';
import { Link } from '@inertiajs/react';
import { FileTextIcon } from 'lucide-react';
import { useState } from 'react';

const dash = <span className="text-subtle-foreground">—</span>;

/** Areas of the deal that arrive with the Phase 2 modules. */
const LATER = [
    ['documentation', 'Documentation'],
    ['execution', 'Execution'],
    ['security', 'Security'],
    ['isin', 'ISIN'],
    ['covenants', 'Covenants'],
    ['credit-rating', 'Credit rating'],
    ['outward', 'Outward'],
    ['invoices', 'Invoices'],
];

function Detail({ label, children, mono = false }) {
    return (
        <div className="min-w-0">
            <dt className="text-xs text-muted-foreground">{label}</dt>
            <dd className={mono ? 'mt-0.5 font-mono text-[13px]' : 'mt-0.5 text-[13px]'}>
                {children || dash}
            </dd>
        </div>
    );
}

function Overview({ deal, letters }) {
    return (
        <div className="flex flex-col gap-4">
            <Card>
                <CardContent>
                    <dl className="grid gap-x-6 gap-y-4 sm:grid-cols-2 lg:grid-cols-4">
                        <Detail label="EL number" mono>
                            {deal.el_number}
                        </Detail>
                        <Detail label="EL date">{formatDate(deal.el_date)}</Detail>
                        <Detail label="Deal code" mono>
                            {deal.deal_code}
                        </Detail>
                        <Detail label="Issue size">{formatMoney(deal.total_issue_size)}</Detail>
                        <Detail label="Issue">
                            {[deal.listing, deal.issue_type].filter(Boolean).join(' · ')}
                        </Detail>
                        <Detail label="Tenure">{deal.tenure}</Detail>
                        <Detail label="Security">
                            {deal.is_secured === null
                                ? null
                                : `${deal.is_secured ? 'Secured' : 'Unsecured'} · ${deal.is_rated ? 'Rated' : 'Unrated'}`}
                        </Detail>
                        <Detail label="Company PAN" mono>
                            {deal.company.pan}
                        </Detail>
                        <Detail label="Vertical team">{deal.vertical_team}</Detail>
                        <Detail label="Relationship manager">{deal.relationship_manager}</Detail>
                        <Detail label="Approved">{formatDate(deal.approved_at)}</Detail>
                        <Detail label="Closed">{formatDate(deal.closed_at)}</Detail>
                    </dl>
                </CardContent>
            </Card>
            <Card>
                <CardHeader className="flex flex-wrap items-center justify-between gap-2">
                    <CardTitle>Engagement letters</CardTitle>
                    <Button variant="outline" size="sm" asChild>
                        <Link href={route('transactions.show', deal.id)}>
                            Fees, schedule and approval
                        </Link>
                    </Button>
                </CardHeader>
                <CardContent>
                    <ul className="flex flex-col divide-y rounded-lg border">
                        {letters.map((l) => (
                            <li
                                key={l.version}
                                className="flex flex-wrap items-center gap-3 px-3 py-2.5"
                            >
                                <FileTextIcon className="size-4 text-muted-foreground" />
                                <div className="min-w-0 flex-1">
                                    <div className="font-mono text-[13px]">
                                        {l.el_number}{' '}
                                        <span className="text-muted-foreground">
                                            · v{l.version}
                                        </span>
                                    </div>
                                    <div className="text-xs text-muted-foreground">
                                        Dated {formatDate(l.el_date)} · generated by{' '}
                                        {l.generated_by}, {formatDateTime(l.generated_at)}
                                        {l.reason && ` · ${l.reason}`}
                                    </div>
                                </div>
                                {l.has_pdf ? (
                                    <Button variant="outline" size="sm" asChild>
                                        <a
                                            href={route('transactions.letter.download', [
                                                deal.id,
                                                l.version,
                                            ])}
                                            target="_blank"
                                            rel="noreferrer"
                                        >
                                            Open PDF
                                        </a>
                                    </Button>
                                ) : (
                                    <span className="text-xs text-muted-foreground">
                                        PDF not copied yet
                                    </span>
                                )}
                            </li>
                        ))}
                    </ul>
                </CardContent>
            </Card>
        </div>
    );
}

function Activity({ items }) {
    if (items.length === 0) {
        return (
            <Empty className="border">
                <EmptyHeader>
                    <EmptyTitle>No activity yet</EmptyTitle>
                </EmptyHeader>
            </Empty>
        );
    }

    return (
        <Card>
            <CardContent>
                <ol className="relative flex flex-col gap-4 border-l pl-5">
                    {items.map((item) => (
                        <li key={item.id} className="relative">
                            <span className="absolute top-1.5 -left-[25px] size-2 rounded-full bg-brand-500" />
                            <div className="flex flex-wrap items-center gap-2 text-[13px]">
                                <Badge variant="neutral">{item.area}</Badge>
                                <span className="font-medium capitalize">{item.event}</span>
                                {item.fields.length > 0 && (
                                    <span className="text-muted-foreground">
                                        {item.fields.map((f) => f.replaceAll('_', ' ')).join(', ')}
                                    </span>
                                )}
                            </div>
                            <div className="text-xs text-muted-foreground">
                                {item.by ?? 'System'} · {formatDateTime(item.at)}
                            </div>
                        </li>
                    ))}
                </ol>
            </CardContent>
        </Card>
    );
}

export default function DealShow({
    tab: initialTab,
    deal,
    letters,
    billing,
    status,
    jobSheet,
    activity,
    can,
}) {
    const [tab, setTab] = useState(initialTab);
    const title = deal.company.name;

    // Keep the open tab in the URL so it survives a refresh and can be shared.
    const changeTab = (value) => {
        setTab(value);
        const url = new URL(window.location.href);
        url.searchParams.set('tab', value);
        window.history.replaceState(window.history.state, '', url);
    };

    return (
        <AppLayout
            title={title}
            breadcrumbs={[{ title: 'Deals', href: route('deals.index') }, { title }]}
        >
            <PageHeader
                title={title}
                description={
                    <span className="flex flex-wrap items-center gap-2">
                        <span className="font-mono">{deal.el_number}</span>
                        <Badge variant={deal.deal_status_tone}>{deal.deal_status_label}</Badge>
                    </span>
                }
            />

            <Tabs value={tab} onValueChange={changeTab}>
                <div className="-mx-1 max-w-full overflow-x-auto px-1">
                    <TabsList>
                        <TabsTrigger value="overview">Overview</TabsTrigger>
                        <TabsTrigger value="billing">Contacts &amp; billing</TabsTrigger>
                        <TabsTrigger value="status">Status</TabsTrigger>
                        <TabsTrigger value="job-sheet">Job sheet</TabsTrigger>
                        <TabsTrigger value="activity">Activity</TabsTrigger>
                        {LATER.map(([value, label]) => (
                            <TabsTrigger
                                key={value}
                                value={value}
                                className="text-muted-foreground"
                            >
                                {label}
                            </TabsTrigger>
                        ))}
                    </TabsList>
                </div>

                <TabsContent value="overview">
                    <Overview deal={deal} letters={letters} />
                </TabsContent>
                <TabsContent value="billing">
                    <BillingPanel deal={deal} billing={billing} canEdit={can.editBilling} />
                </TabsContent>
                <TabsContent value="status">
                    <StatusPanel deal={deal} status={status} canRequest={can.requestStatus} />
                </TabsContent>
                <TabsContent value="job-sheet">
                    <JobSheetPanel dealId={deal.id} rows={jobSheet} can={can} />
                </TabsContent>
                <TabsContent value="activity">
                    <Activity items={activity} />
                </TabsContent>
                {LATER.map(([value, label]) => (
                    <TabsContent key={value} value={value}>
                        <Empty className="border">
                            <EmptyHeader>
                                <EmptyTitle>{label}</EmptyTitle>
                                <EmptyDescription>
                                    Arrives with the Phase 2 modules.
                                </EmptyDescription>
                            </EmptyHeader>
                        </Empty>
                    </TabsContent>
                ))}
            </Tabs>
        </AppLayout>
    );
}
