import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/ui/card';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/Components/ui/dialog';
import { Field, FieldDescription, FieldError, FieldLabel } from '@/Components/ui/field';
import { Input } from '@/Components/ui/input';
import { formatDate, formatDateTime } from '@/lib/format';
import { useForm } from '@inertiajs/react';
import { FileTextIcon, SendIcon } from 'lucide-react';
import { useState } from 'react';

/** Issue the engagement letter (approved transactions) and list every issued version. */
export function LetterPanel({ transactionId, letters, issue }) {
    const [confirming, setConfirming] = useState(false);
    const form = useForm({ el_date: issue?.fixed_date ?? issue?.max_date ?? '' });

    if (!issue && letters.length === 0) return null;

    const submit = (e) => {
        e.preventDefault();
        form.post(route('transactions.letter.issue', transactionId), {
            preserveScroll: true,
            onSuccess: () => setConfirming(false),
        });
    };

    return (
        <Card>
            <CardHeader>
                <CardTitle>Engagement letter</CardTitle>
                <CardDescription>
                    {issue
                        ? 'Approved. Issuing the letter assigns the EL number and deal code and makes the deal active.'
                        : 'Every version of the letter is kept as issued.'}
                </CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col gap-4">
                {issue && (
                    <div className="flex flex-wrap items-end gap-3">
                        <Field className="w-auto" data-invalid={!!form.errors.el_date || undefined}>
                            <FieldLabel htmlFor="el_date">EL date</FieldLabel>
                            <Input
                                id="el_date"
                                type="date"
                                value={form.data.el_date}
                                min={issue.min_date ?? undefined}
                                max={issue.max_date}
                                disabled={!!issue.fixed_date}
                                onChange={(e) => form.setData('el_date', e.target.value)}
                                className="w-44"
                            />
                            {issue.fixed_date && (
                                <FieldDescription>
                                    Fixed: a fee runs from the EL date.
                                </FieldDescription>
                            )}
                        </Field>
                        <Button onClick={() => setConfirming(true)} disabled={!form.data.el_date}>
                            <SendIcon /> Issue letter
                        </Button>
                    </div>
                )}
                <FieldError>{!confirming && form.errors.el_date}</FieldError>

                {letters.length > 0 && (
                    <ul className="flex flex-col divide-y rounded-lg border">
                        {letters.map((l) => (
                            <li
                                key={l.version}
                                className="flex flex-wrap items-center gap-3 px-3 py-2.5"
                            >
                                <FileTextIcon className="size-4 text-muted-foreground" />
                                <div className="min-w-0 flex-1">
                                    <div className="font-mono text-[13px]">
                                        {l.el_number}{' '}
                                        <span className="text-muted-foreground">
                                            · v{l.version}
                                        </span>
                                    </div>
                                    <div className="text-xs text-muted-foreground">
                                        Dated {formatDate(l.el_date)} · generated by{' '}
                                        {l.generated_by}, {formatDateTime(l.generated_at)}
                                        {l.reason && ` · ${l.reason}`}
                                    </div>
                                </div>
                                {l.has_pdf ? (
                                    <Button variant="outline" size="sm" asChild>
                                        <a
                                            href={route('transactions.letter.download', [
                                                transactionId,
                                                l.version,
                                            ])}
                                            target="_blank"
                                            rel="noreferrer"
                                        >
                                            Open PDF
                                        </a>
                                    </Button>
                                ) : (
                                    <span className="text-xs text-muted-foreground">
                                        PDF not copied yet
                                    </span>
                                )}
                            </li>
                        ))}
                    </ul>
                )}
            </CardContent>

            <Dialog
                open={confirming}
                onOpenChange={(open) => !form.processing && setConfirming(open)}
            >
                <DialogContent>
                    <form onSubmit={submit} className="flex flex-col gap-4">
                        <DialogHeader>
                            <DialogTitle>Issue the engagement letter?</DialogTitle>
                            <DialogDescription>
                                This takes the next EL number for the financial year, dated{' '}
                                {formatDate(form.data.el_date)}. A number, once issued, is never
                                reused.
                            </DialogDescription>
                        </DialogHeader>
                        <FieldError>{form.errors.el_date}</FieldError>
                        <DialogFooter>
                            <Button
                                type="button"
                                variant="outline"
                                onClick={() => setConfirming(false)}
                                disabled={form.processing}
                            >
                                Cancel
                            </Button>
                            <Button type="submit" disabled={form.processing}>
                                {form.processing ? 'Issuing…' : 'Issue letter'}
                            </Button>
                        </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog>
        </Card>
    );
}
